// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Login.tsx";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/a.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/details%20copy/1.tsx";
import * as $6 from "./routes/details%20copy/2.tsx";
import * as $7 from "./routes/details/1.tsx";
import * as $8 from "./routes/details/2.tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/ArticleItem.tsx";
import * as $$1 from "./islands/Articleitem2.tsx";
import * as $$2 from "./islands/Articleitem3.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/Example.tsx";
import * as $$5 from "./islands/NavBar.tsx";
import * as $$6 from "./islands/Nav_bar.tsx";

const manifest = {
  routes: {
    "./routes/Login.tsx": $0,
    "./routes/[name].tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/a.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/details%20copy/1.tsx": $5,
    "./routes/details%20copy/2.tsx": $6,
    "./routes/details/1.tsx": $7,
    "./routes/details/2.tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/ArticleItem.tsx": $$0,
    "./islands/Articleitem2.tsx": $$1,
    "./islands/Articleitem3.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/Example.tsx": $$4,
    "./islands/NavBar.tsx": $$5,
    "./islands/Nav_bar.tsx": $$6,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
